# source 'https://dl.cloudsmith.io/basic/orgcs/cocoarepo/cocoapods/index.git'
source 'https://cdn.cocoapods.org/'


use_frameworks!

target 'EkOrrPod_Example' do
  pod 'EkOrrPod', :path => '../'

  target 'EkOrrPod_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    # pod 'AFNetworking', '~> 4.0'
    # Networking
    # pod 'merapodpkg', '~> 1.1.0', :source => 'https://dl.cloudsmith.io/basic/orgcs/cocoarepo/cocoapods/index.git'
    pod 'Alamofire', '~> 5.8'
    pod 'SwiftyJSON', '~> 5.0'
    pod 'ReactiveSwift', '~> 6.7'
    pod 'CocoaLumberjack/Swift', '~> 3.9'
    # pod 'Kingfisher', '~> 7.12'
    pod 'SnapKit', '~> 5.6'
    # pod 'Promises', '~> 1.2'
    pod 'KeychainAccess', '~> 4.2'
    pod 'SwiftDate', '~> 6.0'
    pod 'CryptoSwift', '~> 1.6'
    # pod 'UserNotificationsSwift', '~> 0.7'
    # pod 'MaterialComponents', '~> 122.1'
    # pod 'Swinject', '~> 2.8'

  end
end
