name: Mirror CocoaPods to Cloudsmith

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  push-pods:
    runs-on: ubuntu-latest
    env:
      # Cloudsmith & repo where pods will be published
      CLOUDSMITH_OWNER: orgcs
      CLOUDSMITH_REPO: cocoarepo
      # List of CocoaPods you want to mirror (name@version)
      POD_LIST: |
        Alamofire@5.8.2
        SwiftyJSON@5.0.1  # Corrected from 5.0.2
        ReactiveSwift@6.1.0
        CocoaLumberjack@3.9.3
        Kingfisher@7.0.0
    steps:
      # 1. Checkout this workflow
      - uses: actions/checkout@v4

      # 2. Install Cloudsmith CLI
      - name: Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
          oidc-namespace: ${{ vars.CLOUDSMITH_ORG }}
          oidc-service-slug: ${{ vars.CLOUDSMITH_SERVICESLUG }}

      # 3. Clone the CocoaPods Specs repo
      - name: Clone CocoaPods Specs
        run: |
          git clone https://github.com/CocoaPods/Specs.git ./Specs

      # 4. For each pod, find its podspec and push to Cloudsmith
      - name: Mirror Pods
        shell: bash
        run: |
          set -euo pipefail

          IFS=$'\n'

          for spec in $POD_LIST; do
            name="${spec%@*}"
            version="${spec#*@}"
            echo "=== Processing ${name}@${version} ==="

            # Find the podspec path
            podspec_path=$(find ./Specs -name "${name}.podspec.json" -o -name "${name}.podspec.yaml" | grep "$version" | head -n 1)
            if [ -z "$podspec_path" ]; then
              echo "ERROR: Podspec for ${name}@${version} not found in Specs"
              exit 1
            fi

            # Push to Cloudsmith
            cloudsmith push cocoapods "${CLOUDSMITH_OWNER}/${CLOUDSMITH_REPO}" "$podspec_path" --republish
            echo ">>> Pushed ${name}@${version} to Cloudsmith"
          done