name: Mirror CocoaPods to Cloudsmith

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  mirror-pods:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_OWNER: orgcs
      CLOUDSMITH_REPO: cocoarepo
      POD_LIST: |
        Alamofire@5.8.2
        SwiftyJSON@5.0.2
    steps:
      # Check out the workflow
      - uses: actions/checkout@v4

      # Install Ruby and CocoaPods
      - name: Setup Ruby and CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
      - run: gem install cocoapods

      # Install Cloudsmith CLI
      - name: Cloudsmith CLI aa gya
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.3
        with:
            oidc-namespace: ${{ vars.CLOUDSMITH_ORG }}
            oidc-service-slug: ${{ vars.CLOUDSMITH_SERVICESLUG }}

      # Clone CocoaPods Specs repository
      - name: Clone Specs Repo
        run: git clone https://github.com/CocoaPods/Specs.git ./Specs

      # Process each pod one by one
      - name: Download and Upload Pods
        shell: bash
        run: |
          IFS=$'\n'
          for spec in $POD_LIST; do
            name="${spec%@*}"
            version="${spec#*@}"
            echo "Processing ${name}@${version}"

            # Clear cache and set up working directory
            pod cache clean --all
            mkdir -p packaged
            cd packaged

            # Create a Podfile for the pod
            cat > Podfile << EOF
            platform :ios, '12.0'
            target 'TempTarget' do
              pod '${name}', '${version}'
            end
            EOF

            # Download the pod
            pod install --no-integrate

            # Package the pod into a zip file
            cd "Pods/${name}"
            zip -r "../../${name}.zip" . -x "*.git*"
            cd ../..

            # Upload to Cloudsmith
            cloudsmith push cocoapods \
              "${CLOUDSMITH_OWNER}/${CLOUDSMITH_REPO}" \
              "${name}.zip" \
              --name="${name}" \
              --version="${version}"

            echo "Uploaded ${name}@${version}"

            # Clean up
            cd ..
            rm -rf packaged
          done